### ISSUE TITLE
Maybe it should do chroot?

### ISSUE THREAD

**Issue by e1iu** [jeesyn/mcr-server#1]
https://en.wikipedia.org/wiki/Chroot

**Comment by jingsong-liu** [comment]
When the application run as a daemon, chroot is done. Otherwise, I belive  it is just  run as test mode, and current workspace is usually easy for testing. 
```c
if (daemonize) {
        printf("daemonize mcr-server ...\n");
        /* change work directory to root, redirect stdio to /dev/null. */
        daemon(0, 0);
    }
```

Thx for your reviewing and maybe I should do the chroot in any case.
