### ISSUE TITLE
using stack space as much as possible.

### ISSUE THREAD

**Issue by e1iu** [jeesyn/mcr-server#2]
``` C
void *
cli_conn(void* arg) {
    int sock = ((struct cli_args*)arg)->fd;
    char *wwwroot= ((struct cli_args*)arg)->wwwroot;
    size_t recved = 0;
    int parse_ret = MCR_OK;

    size_t recv_buflen = 80*1024;
    char *recv_buf = malloc(recv_buflen*sizeof(char));   // maybe can use local var instead of heap.
    if (recv_buf == NULL) {
        goto out;
    }
......
}


```

It better for space management , faster than malloc and you don't keep 'free()' in your mind.

**Comment by e1iu** [comment]
http://man7.org/linux/man-pages/man3/pthread_create.3.html

**Comment by jingsong-liu** [comment]
Using stack memory space is fast and convenient but will not be as scalable as using heap memory. We forget about 'free()' it, but there is another rope: the size of stack have have been used or the size of stack memory space remained should be carefully kept in mind when asking more stack memory(not tiny size). 

In this application, `recv_buf ` is used for loading http request.  Buffer within  RLIMIT_NPROC (default 8M on linux-x86) is almost enough to transfer everything (with http chunked encoding).   

So I will use stack space and be careful with adjusting `recv_buflen` value later.
